import { assets } from "../assets/assets";

export const popularproducts = [
    {
    id: 1,
    name: "Samsung Galaxy S23",
    category: "Electronics & Accessories",
    subcategory: "Smartphones & tablets",
    brand: "Samsung",
    price: 1000,
    discount: "15% off",
    img: assets.P_p1,
  },
  {
    id: 2,
    name: "Women Top",
    category: "Fashion & Clothing",
    subcategory: "Women",
    brand: "Zara",
    price: 29.99,
    discount: "15% off",
    img: assets.P_p2,
  },

  {
    id: 3,
    name: "MacBook Air M2",
    category: "Electronics & Accessories",
    subcategory: "Laptops & computers",
    brand: "Apple",
    price: 1500,
    discount: "5% off",
   img: assets.P_p3,
  },
  {
    id: 4,
    name: "Men Hoodie",
    category: "Fashion & Clothing",
    subcategory: "Men",
    brand: "Adidas",
    price: 1400,
    discount: "10% off",
    img: assets.P_p4,
  },
  {
    id: 5,
    name: "JBL Quantum 100",
    category: "Electronics & Accessories",
    subcategory: "Headphones & earphones",
    brand: "JBL",
    price: 250,
    discount: "25% off",
    img: assets.P_p5,
  },
  {
    id: 6,
    name: "Little Boy Hoodie",
    category: "Fashion & Clothing",
    subcategory: "Men",
    brand: "Adidas",
    price: 450,
    discount: "15% off",
    img: assets.P_p6,
  },
];

export const products = [
  /* ========== Electronics & Accessories ========== */
  {
    id: 1,
    name: "Apple iPhone 14",
    category: "Electronics & Accessories",
    subcategory: "Smartphones & tablets",
    brand: "Apple",
    price: 1200,
    discount: "10% off",
    img: "https://images.unsplash.com/photo-1663499482523-1c0c1bae4ce1?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 2,
    name: "Samsung Galaxy S23",
    category: "Electronics & Accessories",
    subcategory: "Smartphones & tablets",
    brand: "Samsung",
    price: 1000,
    discount: "15% off",
    img: "https://images.unsplash.com/photo-1678911820864-e2c567c655d7?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 3,
    name: "MacBook Air M2",
    category: "Electronics & Accessories",
    subcategory: "Laptops & computers",
    brand: "Apple",
    price: 1500,
    discount: "5% off",
    img: "https://images.unsplash.com/photo-1661961111184-11317b40adb2?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 4,
    name: "Dell XPS 13",
    category: "Electronics & Accessories",
    subcategory: "Laptops & computers",
    brand: "Dell",
    price: 1400,
    discount: "10% off",
    img: "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 5,
    name: "JBL Quantum 100",
    category: "Electronics & Accessories",
    subcategory: "Headphones & earphones",
    brand: "JBL",
    price: 250,
    discount: "25% off",
    img: "https://images.unsplash.com/photo-1612444530582-fc66183b16f7?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 6,
    name: "Apple AirPods Pro",
    category: "Electronics & Accessories",
    subcategory: "Headphones & earphones",
    brand: "Apple",
    price: 450,
    discount: "15% off",
    img: "https://images.unsplash.com/photo-1588423770574-91021163dfbb?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 7,
    name: "Anker Power Bank",
    category: "Electronics & Accessories",
    subcategory: "Chargers & power banks",
    brand: "Anker",
    price: 50,
    discount: "5% off",
    img: "https://images.unsplash.com/photo-1609091839697-ebc487fb5b4b?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 8,
    name: "Apple Watch Series 9",
    category: "Electronics & Accessories",
    subcategory: "Smart watches",
    brand: "Apple",
    price: 500,
    discount: "10% off",
    img: "https://images.unsplash.com/photo-1546868871-70ca484456b5?auto=format&fit=crop&q=80&w=500",
  },

  /* ========== Fashion & Clothing ========== */
  {
    id: 9,
    name: "Nike Air Max",
    category: "Fashion & Clothing",
    subcategory: "Shoes",
    brand: "Nike",
    price: 200,
    discount: "10% off",
    img: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 10,
    name: "Adidas Hoodie",
    category: "Fashion & Clothing",
    subcategory: "Men",
    brand: "Adidas",
    price: 80,
    discount: "5% off",
    img: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 11,
    name: "Zara Dress",
    category: "Fashion & Clothing",
    subcategory: "Women",
    brand: "Zara",
    price: 120,
    discount: "15% off",
    img: "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 12,
    name: "Puma Sneakers",
    category: "Fashion & Clothing",
    subcategory: "Shoes",
    brand: "Puma",
    price: 150,
    discount: "10% off",
    img: "https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 13,
    name: "Gucci Bag",
    category: "Fashion & Clothing",
    subcategory: "Bags",
    brand: "Gucci",
    price: 300,
    discount: "20% off",
    img: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 14,
    name: "Nike Shorts",
    category: "Fashion & Clothing",
    subcategory: "Men",
    brand: "Nike",
    price: 50,
    discount: "5% off",
    img: "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 15,
    name: "Adidas Cap",
    category: "Fashion & Clothing",
    subcategory: "Men",
    brand: "Adidas",
    price: 25,
    discount: "0% off",
    img: "https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 16,
    name: "Zara Sandals",
    category: "Fashion & Clothing",
    subcategory: "Women",
    brand: "Zara",
    price: 70,
    discount: "10% off",
    img: "https://images.unsplash.com/photo-1603487742131-4160ec999306?auto=format&fit=crop&q=80&w=500",
  },

  /* ========== Beauty & Personal Care ========== */
  {
    id: 17,
    name: "Nivea Cream",
    category: "Beauty & Personal Care",
    subcategory: "Skincare",
    brand: "Nivea",
    price: 15,
    discount: "0% off",
    img: "https://images.unsplash.com/photo-1626245917164-4ac541294520?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 18,
    name: "Loreal Lipstick",
    category: "Beauty & Personal Care",
    subcategory: "Makeup",
    brand: "Loreal",
    price: 20,
    discount: "5% off",
    img: "https://images.unsplash.com/photo-1586495768811-69632c91bb5b?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 19,
    name: "Maybelline Mascara",
    category: "Beauty & Personal Care",
    subcategory: "Makeup",
    brand: "Maybelline",
    price: 18,
    discount: "5% off",
    img: "https://images.unsplash.com/photo-1631214503951-3751369ede00?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 20,
    name: "Garnier Shampoo",
    category: "Beauty & Personal Care",
    subcategory: "Haircare",
    brand: "Garnier",
    price: 12,
    discount: "0% off",
    img: "https://images.unsplash.com/photo-1624330186493-70028969b596?auto=format&fit=crop&q=80&w=500",
  },

  /* ========== Groceries & Daily Essentials ========== */
  {
    id: 25,
    name: "Nestle Cereal",
    category: "Groceries & Daily Essentials",
    subcategory: "Food",
    brand: "Nestle",
    price: 10,
    discount: "0% off",
    img: "https://images.unsplash.com/photo-1585238342024-78d387f4a707?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 26,
    name: "Coca-Cola 1L",
    category: "Groceries & Daily Essentials",
    subcategory: "Beverages",
    brand: "Coca-Cola",
    price: 2,
    discount: "0% off",
    img: "https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&q=80&w=500",
  },

  /* ========== Automotive & Motor Accessories ========== */
  {
    id: 33,
    name: "Toyota Car Battery",
    category: "Automotive & Motor Accessories",
    subcategory: "Car Accessories",
    brand: "Toyota",
    price: 100,
    discount: "0% off",
    img: "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&q=80&w=500",
  },
  {
    id: 35,
    name: "Mobil Engine Oil",
    category: "Automotive & Motor Accessories",
    subcategory: "Car Accessories",
    brand: "Mobil",
    price: 25,
    discount: "0% off",
    img: "https://images.unsplash.com/photo-1635843104320-99937dfa81e3?auto=format&fit=crop&q=80&w=500",
  },
];